"""Initial Migration

Revision ID: 5388ecf1248d
Revises: None
Create Date: 2014-12-09 00:35:00.798234

"""

# revision identifiers, used by Alembic.
revision = '5388ecf1248d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elogurl', sa.Text(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('shifts', sa.String(), nullable=True),
    sa.Column('personnel', sa.Text(), nullable=True),
    sa.Column('postTime', sa.DateTime(), nullable=True),
    sa.Column('shiftStart', sa.DateTime(), nullable=True),
    sa.Column('shiftEnd', sa.DateTime(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('problems', sa.Text(), nullable=True),
    sa.Column('nextShift', sa.Text(), nullable=True),
    sa.Column('briefSummary', sa.Text(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('usefulBeam', sa.Float(), nullable=True),
    sa.Column('unschedAccDown', sa.Float(), nullable=True),
    sa.Column('unschedUserDown', sa.Float(), nullable=True),
    sa.Column('physAvail', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_report')
    op.drop_table('user')
    ### end Alembic commands ###
